import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import Header from "@/components/header"
import Sidenav from "@/components/sidenav"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex">
          <Sidenav />
          <div className="w-full overflow-x-auto">
            <div className="sm:h-[calc(99vh-60px)] overflow-auto">
              <div className="w-full flex justify-center mx-auto overflow-auto h-[calc(100vh - 120px)] overflow-y-auto relative">
                <div className="w-full md:max-w-7xl">{children}</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}